[package]
name = "shamir-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
sss-rs = "0.12.0"
dialoguer = "0.11.0"
hex = "0.4.3"
aes = "0.8.3"
aes-gcm = "0.10.3"
pbkdf2 = "0.12.2"
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
sha2 = "0.10.8"
